work_dir: ./work_dir/skating/CW334
#weights: ./work_dir/skating/CW/runs-219-4380.pt

# feeder
feeder: feeders.feeder_diving.Feeder
train_feeder_args:
  debug: False
  random_choose: True
  random_move: True
#  window_size: 256
  window_size: 588
  # istrain: True
  # data_path: /share2/SkatingSkeleton2/selected/train_data_25.npy
  # label_path: /share2/SkatingSkeleton2/selected/train_label_25.pkl
  # data_path: /share/skatingDataLgz/train_data_25.npy
  # label_path: /share/skatingDataLgz/train_label_25.pkl
  data_path: share/Skating/train_data_25.npy
  label_path: share/Skating/train_label_25.pkl
#  data_path: /share/Skating_63/skating63_train_data.npy
#  label_path: /share/Skating_63/skating63_train_label.pkl
test_feeder_args:
  debug: False
  window_size: 588
  # istrain: False
  # data_path: /share2/SkatingSkeleton2/selected/val_data_25.npy
  # label_path: /share2/SkatingSkeleton2/selected/val_label_25.pkl
  # data_path: /share/skatingDataLgz/val_data_25.npy
  # label_path: /share/skatingDataLgz/val_label_25.pkl
  data_path: share/Skating/val_data_25.npy
  label_path: share/Skating/val_label_25.pkl
#  data_path: /share/Skating_63/skating63_val_data.npy
#  label_path: /share/Skating_63/skating63_val_label.pkl
  # data_path: /share/skeleton_dataset/Skating/train_data_25.npy
  # label_path: /share/skeleton_dataset/Skating/train_label_25.pkl

#weights: work_dir/skating/base/runs-202-4040.pt
# model
#model: model.FTSGCNjia.Model
model: model.MDRGCN.Model
model_args:
  in_channels: 3
  num_class: 7
  num_person: 1
  num_point: 25
  # edge_importance_weighting: True
  graph: graph.skating.Graph
  graph_args:
    layout: 'openpose25'
    strategy: 'spatial'

#training
# device: [0,1]
# batch_size: 64
# test_batch_size: 64
device: [1]
batch_size: 16
test_batch_size: 48

#optim
base_lr: 0.001
step: [8, 16]
num_epoch: 20
lr_decay_rate: 0.1
warm_up_epoch: 2



seed: 5
